config:
  dockerfile:
    main:
      file: Dockerfile
      context: .
      base_image: ubuntu:14.04

  local:
    docker_toolbox:
      version: 1.12.5
      macos:
        cmd_bash: /bin/bash
        cmd_dockermachine: /usr/local/bin/docker-machine
      windows:
        cmd_bash: c:/Program Files/Git/bin/bash
        cmd_dockermachine: c:/Program Files/Docker Toolbox/docker-machine.exe

    python:
      version: 3.5.2
      pip_version: 8.1.1
      # Invoke is currently pinned by this bug:
      #   https://github.com/pyinvoke/invoke/issues/345
      invoke_version: 0.12.2

  readme:
    working_directory: c:/devel/testwithdocker-base

    docker_toolbox_versions:
      - version: 1.12.5
        windows:
          installer_url: https://github.com/docker/toolbox/releases/download/v1.12.5/DockerToolbox-1.12.5.exe
          install_path: c:/Program Files/Docker Toolbox

    python_versions:
      - version: 3.5.2
        installer_url: https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe
        install_path: c:/Python35
        virtual_environment_name: env35
        requirements_name: requirements3.txt

  travis:
    docker:
      version: 1.11.2-0~trusty
      compose_version: 1.8.0-rc1
      compose_up_delay: 60

compile_config:
  entries:
    - in:  Dockerfile.in
      out: Dockerfile
    - in:  README.md.in
      out: README.md
    - in:  requirements3.in.in
      out: requirements3.in
    - in:  .travis.yml.in
      out: .travis.yml

compile_docker_localize:
  entries:
    - in:  tests/test-compose.yml
      out: tests/test-compose.localized.yml
